source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

project 'RMRPullToRefreshExample.xcodeproj'
workspace 'RMRPullToRefreshExample.xcworkspace'

target :RMRPullToRefreshExample do
	pod 'RMRPullToRefresh', :path => "../"
end
